export const CV = {
  hero: {
    name: 'Diego',
    adress: 'Castillo Román',
    city: 'Valladolid / Valladolid',
    email: 'diego@diegocastillo.es',
    birthDate: '03/11/1978',
    description: 'Front developer',
    phone: '(+12) 3456789210',
    image:
      'https://media-exp1.licdn.com/dms/image/C4E03AQE5wt7AA-U0Cg/profile-displayphoto-shrink_400_400/0/1658343684839?e=1665014400&v=beta&t=RcVoXZSeAFvnkTY98tHVrS2oKApl0bvGDbSwSjTdQ04',
    bckimage:
      'https://media-exp1.licdn.com/dms/image/C4E16AQEdI3wBOPwqWw/profile-displaybackgroundimage-shrink_350_1400/0/1656953864896?e=1665014400&v=beta&t=YSzfPI5yT-vzcQu_wXPjVE4v-YxhVBf0GpyOzkpDznk',
    gitHub: 'https://github.com/diegocastilloupgrade',
    aboutMe: [
      {
        info: 'Vallisoletano de nacimiento, y Madrileño de adopción formado originalmente en Electrónica Industrial pero de vocación en el sector digital.',
      },
      {
        info: 'Tras más de 10 años desarrollando web en HTML y CSS complementé mi carrera como diseñador en UX/UI, rol que he desempeñado durante 4 años.',
      },
      {
        info: 'Mi última etapa laboral ha estado vinculada a la gestión de equipos y terminada esta y tras actualizar mis conocimientos técnicos en el Bootcamp de FullStack mi deseo es el de enfocar mi carrera en el desarrollo front. Aquí, he reforzado mis conocimientos con HTML, CSS, SASS, JS, Angular, React, PHP, NodeJs, GIT.',
      },
      {
        info: 'Todo este recorrido ha permitido que pueda participar en equipos ágiles (SCRUM, KANBAN), empresas de diferentes tamaños (desde Startups hasta multinacionales), desempeñando diversos roles presentes en todo el proceso de desarrollo y así tener una visión holística del producto digital, desde la necesidad de la que surge su desarrollo hasta su puesta en producción.',
      },
    ],
  },
  education: [
    {
      name: 'Bootcamp Full Stack',
      date: '2022',
      where: 'Upgrade Hub',
      educationlogo: '',
      city: 'Madrid',
      desc: 'Bootcamp de Full Stack Developer: HTML, CSS, JS, MongoDB, SQL, NodeJs Angular, React y PHP (Symfony).',
    },
    {
      name: 'CFGS',
      date: '2022',
      where: 'I.E.S. Ribera de Castilla',
      city: 'Valladolid',
      educationlogo: '',
      desc: 'Ciclo Formativo de Grado superior en desarrollo de aplicaciones web (cursando actualmente).',
    },
    {
      name: 'Master en Usabilidad y Experiencia de Usuario',
      date: '2015',
      where: 'Kschool',
      city: 'Madrid',
      educationlogo: '',
      desc: '170h. Programa formativo en Diseño de Experiencia de Usuario y Diseño de Interfaz de usuario.',
    },
    {
      name: 'Programa profesional en Google Analytics',
      date: '2015',
      where: 'Kschool',
      city: 'Madrid',
      educationlogo: '',
      desc: '170h. Programa formativo en Diseño de Experiencia de Usuario y Diseño de Interfaz de usuario.',
    },
    {
      name: 'Google Tag Manager',
      date: '2014',
      where: 'Kschool',
      city: 'Madrid',
      educationlogo: '',
      desc: '16h. Curso avanzado en Google Tag Manager “Mide y Vencerás',
    },
    {
      name: 'Master profesional en postproducción digital de imagen',
      date: '2013',
      where: 'Workshop Experience',
      city: 'Madrid',
      educationlogo: '',
      desc: '160h. Programa avanzado enfocado en la postproducción digital de la imagen.',
    },
    {
      name: 'Master en Fotografía profesional',
      date: '2012',
      where: 'Workshop Experience',
      city: 'Madrid',
      educationlogo: '',
      desc: '160h. Programa formativo de fotografía profesional.',
    },
    {
      name: 'Higher National Diploma en diseño gráfico y multimedia',
      date: '2004',
      where: 'E.S.I. Valladolid',
      city: 'Valladolid',
      educationlogo: '',
      desc: 'Carrera de diseño gráfico y multimedia',
    },
  ],
  experience: [
    {
      where: 'Roams',
      name: 'Project Manager',
      date: '2021 – 2022',
      companylogo: 'logo_roams.jpeg',
      link: 'https://www.roams.es',
      description: 'Project Manager del equipo de desarrollo y producto.',
    },
    {
      where: 'Madison',
      name: 'UX/UI',
      date: '2017 – 2021',
      companylogo: 'logo_madison.jpeg',
      link: '',
      description: 'Diseñador UX/UI en el departamento de Market Research.',
    },
    {
      where: 'Universidad de Valladolid y Burgos',
      name: 'Tutor',
      date: '2018 – 2020',
      companylogo: 'logo_uva.jpeg',
      link: 'http://emprendimientoinnovadorcyl.com/programas-anteriores/',
      description:
        'Tutor en el Programa de apoyo al emprendimiento innovador 2018-2020 para la Universidad de Valladolid, Soria y Burgos.',
    },
    {
      where: 'Freelance',
      name: 'Desarrollador y diseñador UX/UI',
      date: '2016 - 2020',
      link: 'https://diegocastillo.es/portfolio',
      description: 'Desarrollador front end, diseñador UX/UI y gráfico.',
    },
    {
      where: 'Wolters Kluwer España',
      name: 'Desarrollador frontend',
      date: '2007 - 2016',
      companylogo: 'logo_wolters.jpeg',
      link: '',
      description:
        'Desarrollador frontend en el área de desarrollo de software editorial.',
    },
    {
      where: 'Cosmomedia',
      name: 'Desarrollador y diseñador',
      date: '2003 - 2007',
      companylogo: 'logo_cosmomedia.jpeg',
      link: '',
      description: 'Desarrollador Frontend y diseñador gráfico y editorial',
    },
  ],
  languages: {
    language: 'Castellano',
    wrlevel: 'Nativo',
    splevel: 'Nativo',
  },
  habilities: [
    'HTML',
    'SCSS',
    'JS',
    'Angular',
    'React',
    'NodeJs',
    'MongoDB',
    'SQL',
    'GIT',
    'SEO',
    'SCRUM',
    'KANBAN',
    'OKR',
  ],
  volunteer: [
    {
      name: 'September Foundation',
      where: 'MIT',
      description:
        "The September Foundation is a program by Tony Stark to fund schools and young prodigies in their education. The foundation was named by Stark after a lyric from The Fantasticks song, 'Try to Remember,' which he heard his mother sing and play on the piano before her death.",
    },
    {
      name: 'Damage Control',
      where: 'U.S.A.',
      description:
        'The United States Department of Damage Control, occasionally known as the DODC, is a department of the United States of America. Initially a subsidiary of S.H.I.E.L.D., Damage Control was an organization specializing in post-battle clean-up. Following the Battle of New York, Damage Control was made into an executive branch of the United States government, and in a joint venture with Stark Industries, was tasked with acquiring alien and other dangerous artifacts along with cleaning up damages caused by enhanced individuals.',
    },
  ],
};
